### PR TITLE
[FIX] Correct some bugs with V7

### PR DESCRIPTION
**Pull request by YannickB**
Hello,

I tried to use your module with odoo V7 but I had some bugs, especially since ir.wizard.screen no longer exist in V7.

After debugging it, my customer told me at the end to use CSV format so I'll not need this module anymore, but I hope theses corrections may be useful for you.

Regards,
Yannick.

### CODE REVIEW

**Comment by bwrsandman** [comment]
Yannick, could you change the author of the commit. It is displayed as root, which I guess is wrong.

```
git commit --ammend --author="Yannick Buron <yannick.buron@gmail.com>"
```

**Comment by yvaucher** [comment]
Needs a rebase

**Comment by YannickB** [comment]
Sorry for the late reply, shall be ok now

I don't understand the CLA warning, my CLA was submitting a long time ago.

**Comment by yvaucher** [comment]
@YannickB There are still some conflicts which need a rebase

About the CLA, There might be an issue in the script or in your membership data. @gurneyalex ? Any idea about that ?

**Comment by YannickB** [comment]
Unfortunately I still have a lot to learn about rebase (I spent half an 
hour just to change my commit name) and I don't see where are the 
conflicts, can I have your help for it?

**Comment by yvaucher** [comment]
@YannickB 

I guess you rebased it on an outdated branch.

if you `git remote -v` shows origin points to YannickB/connector-sage-50 you were certainly rebasing on https://github.com/yannickb/connector-sage-50/tree/7.0 but you want to rebase on https://github.com/oca/connector-sage-50/tree/7.0

```
git remote add oca git@github.com:OCA/connector-sage-50.git
git fetch oca
git rebase -i oca/7.0
```

Then it will stop on conflict.

Do the required changes in specified files (`git status`)

```
git add <modified files>
git rebase --continue
```

(redo if necessary for each conflicting commits)

**Comment by YannickB** [comment]
Ok thank for the explanation.

During the conflict resolution, I realized that the bugs I wanted to correct was already debugged in the meanwhile, so I think we can close this issue.

**Comment by gurneyalex** [comment]
@YannickB I added your github login in the OCA database, your future contributions should not be flagged by the CLA bot any more.

Thanks for your contributions to OCA.

**Pull request closed without merging**
